# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 00:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_vencimento', models.DateTimeField()),
                ('nome_credor', models.CharField(max_length=50)),
                ('forma_recebimento', models.CharField(max_length=45)),
                ('situacao', models.CharField(choices=[('AB', 'Aberto'), ('PG', 'Pagamento')], max_length=2)),
                ('observacoes', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_entrada', models.DateTimeField()),
                ('nome_pagador', models.CharField(max_length=50)),
                ('forma_recebimento', models.CharField(max_length=45)),
                ('situacao', models.CharField(choices=[('AB', 'Aberto'), ('PG', 'Pagamento')], max_length=2)),
                ('observacoes', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
